# Generated by Django 5.2.5 on 2025-08-25 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artists', models.CharField(blank=True, max_length=255, null=True)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_seconds', models.PositiveSmallIntegerField(null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_provider', models.CharField(default='local', max_length=255)),
                ('password_hash', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, to='account.playlist')),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.PROTECT, to='account.songs')),
            ],
            options={
                'db_table': 'playlist_songs',
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='account.songs')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'user_library',
                'unique_together': {('user', 'song')},
            },
        ),
    ]
